server:
  port: 9191
#  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
            thread:
            timeoutInMilliseconds: 4000
#actuator
management:
endpoints:
web:
exposure:
  include: hystrix.stream
#====
#
#  spring:
#    main: web-application-type=reactive
#  spring:
#     cloud:
#      circuitbreaker:
#      hystrix:
#            enabled: false
